install:
	@echo "Installing..."
	@pip install -r requirements.txt
	@echo "Done."

test:
	@echo "Running tests..."
	@pytest
	@echo "Done."

run:
	@echo "Running..."
	@flask --app lib/app.py run
	@echo "Done."